export const CHANGE_MOVIELIST = "CHANGE_MOVIELIST";
export const CHANGE_SEARCHVALUE = "CHANGE_SEARCHVALUE";
export const CHANGE_ERROR = "CHANGE_ERROR";
export const CHANGE_LOADING = "CHANGE_LOADING";
export const CHANGE_ISSEARCHING = "CHANGE_ISSEARCHING";
